import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import SideNav from '@/app/ui/sidenav';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Prtfolio - MQ Ryder',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className='flex h-screen flex-col lg:flex-row overflow-hidden bg-cyan-50'>
					<div className='w-full flex-none lg:w-64'>
						<SideNav />
					</div>
					<div className='flex-grow overflow-y-auto'>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
